name: Deploy

on:
  push:
    branches:
      - nextra

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn config set registry https://registry.npmmirror.com
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build && yarn export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
