name: build document.

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn config set registry https://registry.npmmirror.com
      - run: yarn --check-files
      - run: yarn build
      - run: mkdir .public
      - run: cp -r build/* .public
      - run: mv .public public